
# --------------------------------------------------------
# basic configuration
# --------------------------------------------------------
VERSION = "0.0.1"                                          # MyScript version
SCRIPT_NAME = 'Myscript.py'                                # final py name generated by build.py
SCRIPTS_POSITION = 'scripts'                               # json scripts content files root folder position

# change color: https://rich.readthedocs.io/en/stable/appendix/colors.html
TITLE_NAME = 'MyScript'
# TITLE_COLOR = 'dodger_blue2'
TITLE_POSITION = 'center'
# ---
CMD_PROMPT = '[MyScript]'                                  # show in command line prompt
CMD_PROMPT_COLOR = 'cyan'                                  # prompt color
INPUT_ACTIVE_STYLE = 'grey15'
# ---
SELECT_ITEM_LANGUAGE_COLOR = 'yellow'
SELECTED_ITEM_PADDING = (0,2)
SELECTED_ITEM_COLOR = 'grey15'
# ---
DISPLAY_LAYOUT_HEADER_SIZE = 3
DISPLAY_LAYOUT_MAIN_RATIO = 1
DISPLAY_LAYOUT_BODY_RATIO = 8
DISPLAY_LAYOUT_BODY_MINSIZE = 60

DISPLAY_ACTIVE_STYLE = 'yellow on grey19'
DISPLAY_CODE_THEME = 'one-dark'
DISPLAY_CODE_BACKGROUND = 'default'
DISPLAY_SHOW_LINE_NUMBER = True
DISPLAY_LINK_COLOR = 'white'
DISPLAY_INFO_COLOR = "green"
DISPLAY_INFO_JUSTIFY = "right"
DISPLAY_INFO_TABLE_PADDING = 1
DISPLAY_INFO_PANEL_PADDING = (1, 2)
# --------------------------------------------------------
# Keyboard input handler
# https://github.com/luzhixing12345/keyboardmap
# --------------------------------------------------------
LOWCASE_CHAR = [chr(i) for i in range(97,123)] 
HIGHCASE_CHAR = [chr(i) for i in range(65,91)]
DIGIT_CHAR = [chr(i) for i in range(48,58)]
SPECIAL_CHAR = [
    '`','~','!','@','#','$','%','^','&','*','(',')','_','-','+','=',\
    '{','[','}',']','|','\\',\
    ':',';','\"','\'',\
    '<',',','>','.','?','/','SPACE'
]
# normal keyboard input
NORMAL_CHAR = LOWCASE_CHAR + HIGHCASE_CHAR + DIGIT_CHAR + SPECIAL_CHAR
# special keyboard input which has some usage
FUNCTION_CHAR = [
    'ESC',          # back to last mode
    'BACKSPACE',    # remove the last character
    'KEY_UP',       # history search words
    'KEY_DOWN',     # history search words
    'KEY_LEFT',     # last md-doc or code
    'KEY_RIGHT',    # next md-doc or code
    'ENTER',        # enter the next mode or run
    'TAB'           # change active position in DISPLAY MODE
]

# --------------------------------------------------------
# program focus mode
# --------------------------------------------------------
INPUT_MODE = 0
SELECT_MODE = 1
DISPLAY_MODE = 2
RUN_MODE = 3

# --------------------------------------------------------
# display active position
# --------------------------------------------------------
HEADER = 'HEADER'
MD_DOC = 'MD-DOC'
CODE = 'CODE'
