
import platform
import select
import datetime
import json
import os
# --------------------------------------------------------
# basic configuration
# --------------------------------------------------------
VERSION = "0.0.1"                                          # MyScript version
UPDATE_TIME = datetime.datetime.now().strftime('%Y-%m-%d') # latest update time
SCRIPT_NAME = 'Myscript.py'                                # final py name generated by build.py
SCRIPTS_POSITION = './scripts'                             # json scripts content files root folder position

# change color: https://rich.readthedocs.io/en/stable/appendix/colors.html
TITLE_NAME = 'MyScript'
TITLE_COLOR = 'blue'
TITLE_POSITION = 'center'
# ---
CMD_PROMPT = '[MyScript]'                                  # show in command line prompt
CMD_PROMPT_COLOR = 'cyan'                                  # prompt color
# ---
ITEM_COLOR = 'grey50'
ITEM_PADDING = (0,2)

# --------------------------------------------------------
# Keyboard input handler
# https://github.com/luzhixing12345/keyboardmap
# --------------------------------------------------------
LOWCASE_CHAR = [chr(i) for i in range(97,123)] 
HIGHCASE_CHAR = [chr(i) for i in range(65,91)]
DIGIT_CHAR = [chr(i) for i in range(48,58)]
SPECIAL_CHAR = [
    '`','~','!','@','#','$','%','^','&','*','(',')','_','-','+','=',\
    '{','[','}',']','|','\\',\
    ':',';','\"','\'',\
    '<',',','>','.','?','/','SPACE'
]
# normal keyboard input
NORMAL_CHAR = LOWCASE_CHAR + HIGHCASE_CHAR + DIGIT_CHAR + SPECIAL_CHAR
# special keyboard input which has some usage
FUNCTION_CHAR = [
    'ESC',          # back to last mode
    'BACKSPACE',    # remove the last character
    'TAB',          # move to next item
    'KEY_UP',       # 
    'KEY_DOWN',
    'KEY_LEFT',
    'KEY_RIGHT',
    'ENTER',
    'SPACE'
]

# --------------------------------------------------------
# program focus mode
# --------------------------------------------------------
INPUT_MODE = 0
SELECT_MODE = 1
DISPLAY_MODE = 2
RUN_MODE = 3